spring:
  jpa:
    database: MYSQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:5432/deposit_service_database
    username: root
    password: root
    driver-class-name: org.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true